#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
git diff origin/Workspace seppuku/.idea/workspace.xml > worksp.out

if [ $(wc -l < worksp.out) -ne 0 ]
then
    cat <<\EOF
Fetch workspace from the Workspace branch

Hint: type "./fixWorkspace.sh" in your terminal emulator   
EOF
	rm -f worksp.out
	exit 1
fi
rm -f worksp.out         

exit 0
                                                     